#!/usr/bin/env bash

# NOTE : This is a poorly written script. Run at your own risk

# If having a separate home directory, then make sure that groups among different distros have the same gid to avoid permission issues.
# It can be done by groupmod command.

# Things to do before running this script:
# If your pip is messed up, remove and install it again.

########################################################################################################################
##                                                      Minimal
## To use the minimal version, run this command:
## curl -fsS https://raw.githubusercontent.com/ganpa3/dotfiles/main/Ubuntu-Install | bash -s -- --minimal
########################################################################################################################
OPTIONS=$(getopt --options amn --longoptions all,minimal,noconfig --name "$0" -- "$@")
eval set -- "$OPTIONS"

MINIMAL=false
NOCONFIG=false
EXTRAS=true

while true; do
    case "$1" in
        -m | --minimal ) MINIMAL=true; shift ;;
        -n | --noconfig ) NOCONFIG=true; shift ;;
        -x | --no-extras ) EXTRAS=false; shift ;;
        -- ) shift; break ;;
        * ) echo "DOBA! Sahi arguments de."; break ;;
    esac
done

if [[ "$MINIMAL" == "true" ]]; then
    sudo apt-get update
    # sudo apt-get upgrade -y
    mkdir -p ~/source ~/C++_Programs
    packages=(
    "zsh"
    "git"
    "build-essential"
    "make"
    "curl"
    "wget"
    "binutils"
    "htop"
    "clangd"
    "clang-format"
    "rsync"
    "neovim"
    "ripgrep"
    )
    sudo apt-get install --fix-missing -y "${packages[@]}"

    if [[ "$NOCONFIG" == "false" ]]; then
        curl -fsS https://raw.githubusercontent.com/ganpa3/dotfiles/main/install.sh | bash
    fi

    if [[ "$EXTRAS" == "true" ]]; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
        pip install --upgrade httpie pgcli
    fi

    exit
fi
########################################################################################################################

# Update the system
sudo apt update
sudo apt upgrade -y
sudo apt-get install -y curl wget git

# Some useful directories
mkdir -p ~/bin
mkdir -p ~/webdev
mkdir -p ~/source
mkdir -p ~/C++_Programs
mkdir -p ~/Python_Programs

# Login without password
sudo sed -i '1i auth sufficient pam_succeed_if.so user ingroup adm' /etc/pam.d/gdm-password
# Reverse it
#sudo sed -i '1d' /etc/pam.d/gdm-password

########################################################################################################################
##                                             GNOME specific settings
########################################################################################################################
# Super + D to show desktop
gsettings set org.gnome.desktop.wm.keybindings show-desktop "['<Super>d']"
# This is used to set custom shortcuts in GNOME
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ name 'Chrome'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ command 'google-chrome'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ binding '<Super>b'

gsettings set org.gnome.desktop.wm.keybindings switch-applications "[]"
gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.desktop.wm.keybindings show-desktop "['<Super>d']"
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Super>Tab', '<Alt>Tab']"
gsettings set org.gnome.nautilus.preferences always-use-location-entry true
gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
gsettings set org.gtk.Settings.FileChooser show-hidden true
########################################################################################################################

# Subllime Text
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

# Github CLI
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
sudo apt-add-repository -y https://cli.github.com/packages

sudo apt-get update

packages=(
"git"
"build-essential"
"python3-dev"
"openjdk-15-jdk"
"openjdk-15-jre"
"pkg-config"
"cmake"
"clang"
"make"
"curl"
"wget"
"golang-go"
"bison"
"binutils"
"fakeroot"
"htop"
"clangd"
"clang-format"
"vlc"
"neovim"
"tree"
"neofetch"
"ranger"
"redshift"
"mtools"
"feh"
"tmux"
"gparted"
"papirus-icon-theme"
"apt-transport-https"
"qbittorrent"
"shellcheck"
"dconf-editor"
"dunst"
"libnotify-bin"
"ffmpeg"
# "regolith-desktop-mobile" # OR regolith-desktop-standard for desktop
"alacritty"
"sublime-text"
"code"
"gh"
"qbittorrent"
"ubuntu-restricted-extras" # Keep this at last, since it involves agreeing to a license.
)

sudo apt-get install --fix-missing -y "${packages[@]}"

pip install --upgrade httpie pgcli

# Install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y

# Updates all the pip packages and install some
pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U
pip3 install black selenium scrapy virtualenvwrapper

# Installing nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

# Installing latest node version and npm packages
nvm install node
npm install -g serve yarn prettier
